# This is a basic workflow that is manually triggered

name: Build Docker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      shairport_sync_branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Shairport Sync git ref'
        # Default value if no value is explicitly provided
        default: 'origin/docker'
        # Input has to be provided for the workflow to run
        required: true
      nqptp_branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'NQPTP git ref'
        # Default value if no value is explicitly provided
        default: 'development'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  docker_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - uses: actions/checkout@v3
      with:
        repository: 'yubiuser/shairport-sync'
        ref: '${{ github.event.inputs.shairport_sync_branch }}'
      
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        build-args: |
          SHAIRPORT_SYNC_BRANCH=${{ github.event.inputs.shairport_sync_branch }}
          NQPTP_BRANCH=${{ github.event.inputs.nqptp_branch }}
        platforms: linux/amd64
        push: false
        tags: a1ex4/snapcast-shairpot-librespot:latest
      
