# This is a basic workflow that is manually triggered

name: Build Docker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      shairport_sync_branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Shairport Sync git ref'
        # Default value if no value is explicitly provided
        default: 'docker'
        # Input has to be provided for the workflow to run
        required: true
      nqptp_branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'NQPTP git ref'
        # Default value if no value is explicitly provided
        default: 'development'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  # Build Shairport Sync with yubiuser/shairport-sync fork
  shairport:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - uses: actions/checkout@v3
      with:
        repository: 'yubiuser/shairport-sync'
        ref: '${{ github.event.inputs.shairport_sync_branch }}'
      
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Shairport Sync
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        build-args: |
          SHAIRPORT_SYNC_BRANCH=${{ github.event.inputs.shairport_sync_branch }}
          NQPTP_BRANCH=${{ github.event.inputs.nqptp_branch }}
        platforms: linux/amd64
        tags: a1ex4/shairport-sync:latest
        outputs: type=docker,dest=/tmp/myimage.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/myimage.tar

  snapcast:
    runs-on: ubuntu-latest
    needs: shairport
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Snapserver image
        uses: docker/build-push-action@v4
        with:
          # context: .
          # file: ./Dockerfile
          platforms: linux/amd64
          push: false